# Starship Configuration - Rainbow Style (P10k mimic)
add_newline = true

format = """
[╭─](244)\
$os\
$directory\
$git_branch\
$git_status\
$fill\
$cmd_duration\
$nodejs\
$python\
$rust\
$golang\
$time\
$line_break\
[╰─](244)\
$character"""

# Move the rest to the right
[fill]
symbol = " "

[os]
disabled = false
style = "bg:#111111 fg:#eeeeee"
format = "[ $symbol ]($style)"

[os.symbols]
Linux = ""
Macos = ""
Windows = ""
Android = ""
Raspbian = ""
Ubuntu = ""
Debian = ""
Arch = ""
CentOS = ""
Fedora = ""
Alpine = ""
Amazon = ""

[directory]
style = "bg:#444444 fg:#ffffff"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
read_only = " "

[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
style = "bg:#222222 fg:#ffffff"
format = "[[ $symbol$branch ](bg:#222222 fg:#ffffff)]($style)"
symbol = " "

[git_status]
style = "bg:#222222 fg:#ffffff"
format = "[[($all_status$ahead_behind )](bg:#222222 fg:#ffffff)]($style)"

[nodejs]
style = "bg:#333333 fg:#88cc88"
format = "[  $version ]($style)"

[python]
style = "bg:#333333 fg:#ffeeaa"
format = "[  $version ]($style)"

[rust]
style = "bg:#333333 fg:#ffccaa"
format = "[  $version ]($style)"

[golang]
style = "bg:#333333 fg:#aaeeff"
format = "[ ﳑ $version ]($style)"

[cmd_duration]
style = "fg:#eedd11"
format = "[  $duration ]($style)"

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "fg:#aaaaaa"
format = "[  $time ]($style)"

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
